# Generated by Django 3.1.4 on 2021-08-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DecimalField(decimal_places=6, help_text='Enter time in seconds', max_digits=20)),
                ('movement', models.CharField(choices=[('up', 'up'), ('down', 'down'), ('left', 'left'), ('right', 'right'), ('stop', 'right')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Move',
                'verbose_name_plural': 'Moves',
                'ordering': ('-id',),
            },
        ),
    ]
